# Generated by Django 6.0.1 on 2026-02-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
    ]
