# Generated by Django 6.0.1 on 2026-02-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_rename_image_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
