# Generated by Django 6.0.1 on 2026-02-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0017_remove_post_status_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
